name: fix code styling

on:
  workflow_call:
    inputs:
      php:
        default: "8.2"
        type: string
      message:
        default: Fix code styling
        type: string
      fix:
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2, laravel/pint
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Run Pint
        run: pint

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: ${{ inputs.message }}
