name: compile assets

on:
  workflow_call:
    inputs:
      node:
        default: "lts/*"
        type: string
      cmd:
        default: "production"
        type: string
      build_path:
        default: "public/"
        type: string

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run ${{ inputs.cmd }}

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: Compile Assets
          file_pattern: ${{ inputs.build_path }}
