name: normalize every composer.json files

on:
  workflow_call:
    inputs:
      php:
        default: "8.4"
        type: string
      message:
        default: Normalize every composer.json file
        type: string
      fix:
        default: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2, composer-normalize
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Normalize every composer.json files
        run: find . -path "*/vendor" -prune -o -name "composer.json" -print -exec composer normalize {} \;

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}
